backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "wallpapers"
    label: "Wallpapers"
    file: "public/wallpapers.json"
    label_singular: "Wallpaper"
    description: "Add, edit, and manage all wallpapers here."
    fields:
      - {label: "ID", name: "id", widget: "string", hint: "A unique ID, e.g., nature001"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Author"
        name: "author"
        widget: "object"
        fields:
          - {label: "Author Name", name: "name", widget: "string"}
          - {label: "Author Title", name: "title", widget: "string"}
      - {label: "Upload Date", name: "upload_date", widget: "datetime", default: "", format: "YYYY-MM-DD", hidden: true}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", hint: "Press enter after each tag"}
      - label: "Download Options"
        name: "download_options"
        widget: "list"
        summary: "{{fields.resolution}} | {{fields.path}}"
        fields:
          - {label: "Resolution", name: "resolution", widget: "select", options: ["1080p", "2K", "4K", "8K", "Mobile"]}
          - {label: "File", name: "path", widget: "file"}
